# NOTE: Please do not edit this file, it was auto generated by jhconvert
#       See http://wiki.sugarlabs.org/go/Deployment_Team/jhconvert for details
%define _disable_ld_no_undefined 1
 
Name:		sugar-base
Version:	0.98.0
Release:	3
Summary:	Base Sugar library
License:	LGPLv2
Group:		Graphical desktop/Other
Url:		http://sugarlabs.org/

Source0:	http://download.sugarlabs.org/sources/sucrose/glucose/sugar-base/sugar-base-%{version}.tar.bz2

Requires:	python2-dbus  
Requires:	python2-decorator  
Requires:	python2-gobject >= 2.15
Requires:	pygtk2.0  
Requires:	python2 
Requires:	unzip  

BuildRequires:	perl-XML-Parser  
BuildRequires:	gettext  
BuildRequires:	intltool >= 0.33
BuildRequires:	pkgconfig  
BuildRequires:	python2-gobject-devel >= 2.15
BuildRequires:	pygtk2.0-devel  
BuildRequires:	python2-devel  


%description
The base libary for Sugar. It provides helpers for the development
of services and activities.

%prep
%setup -q 


%build
export PYTHON=python2
%configure2_5x
%make

%install
make DESTDIR=%{buildroot} install
install -d -m 0755 %{buildroot}/%{_datadir}/sugar/activities
%find_lang sugar-base


%files -f sugar-base.lang
%dir %{_datadir}/sugar
%dir %{_datadir}/sugar/activities
%{python2_sitelib}/*
%doc COPYING NEWS


